// Auto-generated by content/scripts/generate-locales.js — DO NOT EDIT
// Run `pnpm copy:generate` to regenerate this file

import enCOCommon from '@/content/locales/en/co/common.json'
import enCOConfirmInfo from '@/content/locales/en/co/confirmInfo.json'
import enCODisclaimer from '@/content/locales/en/co/disclaimer.json'
import enCOEmail from '@/content/locales/en/co/email.json'
import enCOEnterEmail from '@/content/locales/en/co/enterEmail.json'
import enCOLanding from '@/content/locales/en/co/landing.json'
import enCOLanguage from '@/content/locales/en/co/language.json'
import enCOOptionalId from '@/content/locales/en/co/optionalId.json'
import enCOPersonalInfo from '@/content/locales/en/co/personalInfo.json'
import enCOResult from '@/content/locales/en/co/result.json'
import enCOText from '@/content/locales/en/co/text.json'
import enCOValidation from '@/content/locales/en/co/validation.json'
import enDCCommon from '@/content/locales/en/dc/common.json'
import enDCConfirmInfo from '@/content/locales/en/dc/confirmInfo.json'
import enDCDisclaimer from '@/content/locales/en/dc/disclaimer.json'
import enDCEmail from '@/content/locales/en/dc/email.json'
import enDCEnterEmail from '@/content/locales/en/dc/enterEmail.json'
import enDCLanding from '@/content/locales/en/dc/landing.json'
import enDCLanguage from '@/content/locales/en/dc/language.json'
import enDCOptionalId from '@/content/locales/en/dc/optionalId.json'
import enDCPersonalInfo from '@/content/locales/en/dc/personalInfo.json'
import enDCResult from '@/content/locales/en/dc/result.json'
import enDCText from '@/content/locales/en/dc/text.json'
import enDCValidation from '@/content/locales/en/dc/validation.json'
import esCOCommon from '@/content/locales/es/co/common.json'
import esCOConfirmInfo from '@/content/locales/es/co/confirmInfo.json'
import esCODisclaimer from '@/content/locales/es/co/disclaimer.json'
import esCOEmail from '@/content/locales/es/co/email.json'
import esCOEnterEmail from '@/content/locales/es/co/enterEmail.json'
import esCOLanding from '@/content/locales/es/co/landing.json'
import esCOLanguage from '@/content/locales/es/co/language.json'
import esCOOptionalId from '@/content/locales/es/co/optionalId.json'
import esCOPersonalInfo from '@/content/locales/es/co/personalInfo.json'
import esCOResult from '@/content/locales/es/co/result.json'
import esCOText from '@/content/locales/es/co/text.json'
import esCOValidation from '@/content/locales/es/co/validation.json'
import esDCCommon from '@/content/locales/es/dc/common.json'
import esDCConfirmInfo from '@/content/locales/es/dc/confirmInfo.json'
import esDCDisclaimer from '@/content/locales/es/dc/disclaimer.json'
import esDCEmail from '@/content/locales/es/dc/email.json'
import esDCEnterEmail from '@/content/locales/es/dc/enterEmail.json'
import esDCLanding from '@/content/locales/es/dc/landing.json'
import esDCLanguage from '@/content/locales/es/dc/language.json'
import esDCOptionalId from '@/content/locales/es/dc/optionalId.json'
import esDCPersonalInfo from '@/content/locales/es/dc/personalInfo.json'
import esDCResult from '@/content/locales/es/dc/result.json'
import esDCText from '@/content/locales/es/dc/text.json'
import esDCValidation from '@/content/locales/es/dc/validation.json'

export const stateResources = {
  co: {
    en: {
      common: enCOCommon,
      confirmInfo: enCOConfirmInfo,
      disclaimer: enCODisclaimer,
      email: enCOEmail,
      enterEmail: enCOEnterEmail,
      landing: enCOLanding,
      language: enCOLanguage,
      optionalId: enCOOptionalId,
      personalInfo: enCOPersonalInfo,
      result: enCOResult,
      text: enCOText,
      validation: enCOValidation,
    },
    es: {
      common: esCOCommon,
      confirmInfo: esCOConfirmInfo,
      disclaimer: esCODisclaimer,
      email: esCOEmail,
      enterEmail: esCOEnterEmail,
      landing: esCOLanding,
      language: esCOLanguage,
      optionalId: esCOOptionalId,
      personalInfo: esCOPersonalInfo,
      result: esCOResult,
      text: esCOText,
      validation: esCOValidation,
    },
  },
  dc: {
    en: {
      common: enDCCommon,
      confirmInfo: enDCConfirmInfo,
      disclaimer: enDCDisclaimer,
      email: enDCEmail,
      enterEmail: enDCEnterEmail,
      landing: enDCLanding,
      language: enDCLanguage,
      optionalId: enDCOptionalId,
      personalInfo: enDCPersonalInfo,
      result: enDCResult,
      text: enDCText,
      validation: enDCValidation,
    },
    es: {
      common: esDCCommon,
      confirmInfo: esDCConfirmInfo,
      disclaimer: esDCDisclaimer,
      email: esDCEmail,
      enterEmail: esDCEnterEmail,
      landing: esDCLanding,
      language: esDCLanguage,
      optionalId: esDCOptionalId,
      personalInfo: esDCPersonalInfo,
      result: esDCResult,
      text: esDCText,
      validation: esDCValidation,
    },
  },
}

export const namespaces = ['common', 'confirmInfo', 'disclaimer', 'email', 'enterEmail', 'landing', 'language', 'optionalId', 'personalInfo', 'result', 'text', 'validation'] as const
export type Namespace = (typeof namespaces)[number]
