// Auto-generated by content/scripts/generate-locales.js — DO NOT EDIT
// Run `pnpm copy:generate` to regenerate this file

import enCOCommon from '@/content/locales/en/co/common.json'
import enCOConfirmInfo from '@/content/locales/en/co/confirmInfo.json'
import enCODisclaimer from '@/content/locales/en/co/disclaimer.json'
import enCOLanding from '@/content/locales/en/co/landing.json'
import enCOOptionalId from '@/content/locales/en/co/optionalId.json'
import enCOPersonalInfo from '@/content/locales/en/co/personalInfo.json'
import enCOResult from '@/content/locales/en/co/result.json'
import enDCCommon from '@/content/locales/en/dc/common.json'
import enDCConfirmInfo from '@/content/locales/en/dc/confirmInfo.json'
import enDCDisclaimer from '@/content/locales/en/dc/disclaimer.json'
import enDCLanding from '@/content/locales/en/dc/landing.json'
import enDCOptionalId from '@/content/locales/en/dc/optionalId.json'
import enDCPersonalInfo from '@/content/locales/en/dc/personalInfo.json'
import enDCResult from '@/content/locales/en/dc/result.json'
import esCOCommon from '@/content/locales/es/co/common.json'
import esCOConfirmInfo from '@/content/locales/es/co/confirmInfo.json'
import esCODisclaimer from '@/content/locales/es/co/disclaimer.json'
import esCOLanding from '@/content/locales/es/co/landing.json'
import esCOOptionalId from '@/content/locales/es/co/optionalId.json'
import esCOPersonalInfo from '@/content/locales/es/co/personalInfo.json'
import esCOResult from '@/content/locales/es/co/result.json'
import esDCCommon from '@/content/locales/es/dc/common.json'
import esDCConfirmInfo from '@/content/locales/es/dc/confirmInfo.json'
import esDCDisclaimer from '@/content/locales/es/dc/disclaimer.json'
import esDCLanding from '@/content/locales/es/dc/landing.json'
import esDCOptionalId from '@/content/locales/es/dc/optionalId.json'
import esDCPersonalInfo from '@/content/locales/es/dc/personalInfo.json'
import esDCResult from '@/content/locales/es/dc/result.json'

export const stateResources = {
  co: {
    en: {
      common: enCOCommon,
      confirmInfo: enCOConfirmInfo,
      disclaimer: enCODisclaimer,
      landing: enCOLanding,
      optionalId: enCOOptionalId,
      personalInfo: enCOPersonalInfo,
      result: enCOResult,
    },
    es: {
      common: esCOCommon,
      confirmInfo: esCOConfirmInfo,
      disclaimer: esCODisclaimer,
      landing: esCOLanding,
      optionalId: esCOOptionalId,
      personalInfo: esCOPersonalInfo,
      result: esCOResult,
    },
  },
  dc: {
    en: {
      common: enDCCommon,
      confirmInfo: enDCConfirmInfo,
      disclaimer: enDCDisclaimer,
      landing: enDCLanding,
      optionalId: enDCOptionalId,
      personalInfo: enDCPersonalInfo,
      result: enDCResult,
    },
    es: {
      common: esDCCommon,
      confirmInfo: esDCConfirmInfo,
      disclaimer: esDCDisclaimer,
      landing: esDCLanding,
      optionalId: esDCOptionalId,
      personalInfo: esDCPersonalInfo,
      result: esDCResult,
    },
  },
}

export const namespaces = ['common', 'confirmInfo', 'disclaimer', 'landing', 'optionalId', 'personalInfo', 'result'] as const
export type Namespace = (typeof namespaces)[number]
