version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "pip"
    directory: "tofu/modules/sebt_database/lambda"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "pip"
    directory: "tofu/modules/sebt_ses/lambda"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directories:
      - "/tofu/modules/*"
      - "/tofu/config/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      cfa-tofu-modules:
        patterns:
          - "*"
