packages:
  - src/SEBT.Portal.Web
  - src/SEBT.EnrollmentChecker.Web
  - packages/*

overrides:
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=4.0.0 <5.0.5: '>=5.0.5'
  path-to-regexp@<0.1.13: '>=0.1.13'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  smol-toml@<1.6.1: '>=1.6.1'
  tmp@<=0.2.3: '>=0.2.4'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
