import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import {
  applyOrder,
  buildParentToc,
  buildToc,
  formatStampDate,
  lastCommitDate,
  listMarkdown,
  SECTIONS,
  stampLastUpdated,
} from './generate-doc-sections.ts';

test('toc lists the authored index first when a section has one', () => {
  const toc = buildToc(['0001-first.md', '0002-second.md'], true);

  assert.match(toc, /Generated by scripts\/docs\/generate-doc-sections\.ts/);
  assert.ok(toc.indexOf('index.md') < toc.indexOf('0001-first.md'), 'index should come first');
  assert.ok(toc.indexOf('0001-first.md') < toc.indexOf('0002-second.md'), 'file order should be preserved');
});

test('toc omits the index entry for sections without one', () => {
  const toc = buildToc(['building-a-state-connector.md'], false);

  assert.ok(!toc.includes('index.md'), `should not reference an index:\n${toc}`);
  assert.match(toc, /building-a-state-connector\.md/);
});

test('toc entries carry no name, so docfx derives it from each H1', () => {
  const toc = buildToc(['0001-first.md'], true);

  assert.ok(!toc.includes('name:'), `entries should be href-only:\n${toc}`);
});

test('lists only Markdown files, sorted by filename', () => {
  const dir = mkdtempSync(join(tmpdir(), 'doc-sections-'));
  for (const name of ['0002-second.md', '0001-first.md', 'notes.txt']) {
    writeFileSync(join(dir, name), '# heading\n');
  }
  mkdirSync(join(dir, 'nested'));

  assert.deepEqual(listMarkdown(dir), ['0001-first.md', '0002-second.md']);
});

test('applyOrder puts named files first, in the given order', () => {
  const files = ['contract.md', 'data-mapping.md', 'index.md', 'quickstart.md'];

  assert.deepEqual(applyOrder(files, ['index.md', 'quickstart.md', 'contract.md']), [
    'index.md',
    'quickstart.md',
    'contract.md',
    'data-mapping.md',
  ]);
});

test('applyOrder keeps unnamed files, so a new page still reaches the nav', () => {
  const ordered = applyOrder(['index.md', 'new-page.md'], ['index.md']);

  assert.deepEqual(ordered, ['index.md', 'new-page.md']);
});

test('applyOrder ignores names with no matching file', () => {
  assert.deepEqual(applyOrder(['index.md'], ['index.md', 'deleted.md']), ['index.md']);
});

test('applyOrder without an order falls back to the given sequence', () => {
  assert.deepEqual(applyOrder(['a.md', 'b.md']), ['a.md', 'b.md']);
});

test("each section's ordered names exist in its source directory", () => {
  const repoRoot = resolve(fileURLToPath(import.meta.url), '../../..');

  for (const section of SECTIONS.filter((s) => s.order)) {
    const present = listMarkdown(join(repoRoot, section.source));
    for (const name of section.order ?? []) {
      assert.ok(present.includes(name), `${section.source} has no ${name}, so the order entry is stale`);
    }
  }
});

test('a nav path becomes nested headings, with the section index as the leaf href', () => {
  const toc = parse(
    buildParentToc([{ nav: ['Content', 'Customizing', 'Change user-facing text'], dir: 'content', files: ['index.md', 'add-a-key.md'] }]),
  );

  assert.deepEqual(toc, [
    {
      name: 'Content',
      items: [
        {
          name: 'Customizing',
          items: [
            {
              name: 'Change user-facing text',
              href: 'content/index.md',
              items: [{ href: 'content/add-a-key.md' }],
            },
          ],
        },
      ],
    },
  ]);
});

test('sections that share a leading nav name share one heading node', () => {
  const toc = parse(
    buildParentToc([
      { nav: ['Get started', 'First guide'], dir: 'first', files: ['index.md'] },
      { nav: ['Get started', 'Second guide'], dir: 'second', files: ['index.md'] },
    ]),
  );

  assert.equal(toc.length, 1, `expected one shared heading:\n${JSON.stringify(toc)}`);
  assert.deepEqual(
    toc[0].items.map((entry: { name: string }) => entry.name),
    ['First guide', 'Second guide'],
  );
});

test('a section with only an index carries no empty child list', () => {
  const toc = parse(buildParentToc([{ nav: ['Guides', 'Solo'], dir: 'solo', files: ['index.md'] }]));

  assert.deepEqual(toc[0].items[0], { name: 'Solo', href: 'solo/index.md' });
});

test('a section without an index leaves its heading unlinked', () => {
  const toc = parse(buildParentToc([{ nav: ['Guides', 'No landing'], dir: 'none', files: ['first.md'] }]));

  assert.deepEqual(toc[0].items[0], { name: 'No landing', items: [{ href: 'none/first.md' }] });
});

test('a grouped section without a nav path is rejected', () => {
  assert.throws(() => buildParentToc([{ nav: [], dir: 'orphan', files: ['index.md'] }]), /nowhere to sit/);
});

test('every grouped section declares a nav path ending in its own label', () => {
  for (const section of SECTIONS.filter((s) => s.parent)) {
    assert.ok(section.nav && section.nav.length > 0, `${section.source} is grouped but declares no nav path`);
  }
});

test('every configured section outputs inside the docfx site', () => {
  for (const section of SECTIONS) {
    assert.ok(section.output.startsWith('docs/docfx/'), `${section.source} writes outside the site: ${section.output}`);
    assert.ok(!section.source.startsWith('docs/docfx/'), `${section.source} would copy the site into itself`);
  }
});

test('the last-updated stamp goes directly below the H1', () => {
  const stamped = stampLastUpdated('# Title\n\nBody text.\n', '2026-09-03T08:54:14-06:00', 'docs/guides/content/index.md');
  const lines = stamped.split('\n');

  assert.equal(lines[0], '# Title');
  assert.match(stamped, /<p class="doc-meta">Last updated <time datetime="2026-09-03">September 3, 2026<\/time>/);
  assert.match(stamped, /docs\/guides\/content\/index\.md/);
  assert.ok(stamped.endsWith('Body text.\n'), 'body should be preserved');
});

test('the stamp lands below the H1 even when front matter precedes it', () => {
  const stamped = stampLastUpdated('---\nkeywords: i18n\n---\n\n# Title\n\nBody.\n', '2026-01-09T00:00:00Z', 'a.md');
  const lines = stamped.split('\n');

  assert.equal(lines[0], '---', 'front matter must stay first or docfx stops parsing it');
  assert.ok(lines.indexOf('# Title') < lines.findIndex((l) => l.includes('doc-meta')));
});

test('a page with no H1 is returned unchanged rather than mangled', () => {
  const source = 'Just a paragraph.\n';

  assert.equal(stampLastUpdated(source, '2026-09-03T00:00:00Z', 'a.md'), source);
});

test('the stamp date is read from the string, so no timezone can shift the day', () => {
  // 23:30 UTC-7 is the next day in UTC. Date parsing would report the 4th.
  assert.equal(formatStampDate('2026-09-03T23:30:00-07:00'), 'September 3, 2026');
  assert.equal(formatStampDate('2026-01-01T00:00:00+13:00'), 'January 1, 2026');
});

test('git reports no date for a path it does not track', () => {
  const repoRoot = resolve(fileURLToPath(import.meta.url), '../../..');

  assert.equal(lastCommitDate(repoRoot, 'docs/docfx/guides/content/index.md'), null, 'generated copies are git-ignored');
  assert.match(lastCommitDate(repoRoot, 'docs/guides/content/index.md') ?? '', /^\d{4}-\d{2}-\d{2}T/);
});
