import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { applyOrder, buildToc, listMarkdown, SECTIONS } from './generate-doc-sections.ts';

test('toc lists the authored index first when a section has one', () => {
  const toc = buildToc(['0001-first.md', '0002-second.md'], true);

  assert.match(toc, /Generated by scripts\/docs\/generate-doc-sections\.ts/);
  assert.ok(toc.indexOf('index.md') < toc.indexOf('0001-first.md'), 'index should come first');
  assert.ok(toc.indexOf('0001-first.md') < toc.indexOf('0002-second.md'), 'file order should be preserved');
});

test('toc omits the index entry for sections without one', () => {
  const toc = buildToc(['building-a-state-connector.md'], false);

  assert.ok(!toc.includes('index.md'), `should not reference an index:\n${toc}`);
  assert.match(toc, /building-a-state-connector\.md/);
});

test('toc entries carry no name, so docfx derives it from each H1', () => {
  const toc = buildToc(['0001-first.md'], true);

  assert.ok(!toc.includes('name:'), `entries should be href-only:\n${toc}`);
});

test('lists only Markdown files, sorted by filename', () => {
  const dir = mkdtempSync(join(tmpdir(), 'doc-sections-'));
  for (const name of ['0002-second.md', '0001-first.md', 'notes.txt']) {
    writeFileSync(join(dir, name), '# heading\n');
  }
  mkdirSync(join(dir, 'nested'));

  assert.deepEqual(listMarkdown(dir), ['0001-first.md', '0002-second.md']);
});

test('applyOrder puts named files first, in the given order', () => {
  const files = ['contract.md', 'data-mapping.md', 'index.md', 'quickstart.md'];

  assert.deepEqual(applyOrder(files, ['index.md', 'quickstart.md', 'contract.md']), [
    'index.md',
    'quickstart.md',
    'contract.md',
    'data-mapping.md',
  ]);
});

test('applyOrder keeps unnamed files, so a new page still reaches the nav', () => {
  const ordered = applyOrder(['index.md', 'new-page.md'], ['index.md']);

  assert.deepEqual(ordered, ['index.md', 'new-page.md']);
});

test('applyOrder ignores names with no matching file', () => {
  assert.deepEqual(applyOrder(['index.md'], ['index.md', 'deleted.md']), ['index.md']);
});

test('applyOrder without an order falls back to the given sequence', () => {
  assert.deepEqual(applyOrder(['a.md', 'b.md']), ['a.md', 'b.md']);
});

test("each section's ordered names exist in its source directory", () => {
  const repoRoot = resolve(fileURLToPath(import.meta.url), '../../..');

  for (const section of SECTIONS.filter((s) => s.order)) {
    const present = listMarkdown(join(repoRoot, section.source));
    for (const name of section.order ?? []) {
      assert.ok(present.includes(name), `${section.source} has no ${name}, so the order entry is stale`);
    }
  }
});

test('every configured section outputs inside the docfx site', () => {
  for (const section of SECTIONS) {
    assert.ok(section.output.startsWith('docs/docfx/'), `${section.source} writes outside the site: ${section.output}`);
    assert.ok(!section.source.startsWith('docs/docfx/'), `${section.source} would copy the site into itself`);
  }
});
