<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
      <HomeDir Condition="'$(OS)' == 'Windows_NT'">$(USERPROFILE)</HomeDir>
      <HomeDir Condition="'$(HomeDir)' == ''">$(HOME)</HomeDir>
    </PropertyGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="SEBT.Portal.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="libphonenumber-csharp" Version="9.0.30" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />      
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../SEBT.Portal.Kernel/SEBT.Portal.Kernel.csproj" />
    </ItemGroup>

</Project>
