using Bogus;
using Microsoft.EntityFrameworkCore;
using SEBT.Portal.Core.Models.Auth;
using SEBT.Portal.Infrastructure.Data;
using SEBT.Portal.Infrastructure.Data.Entities;

namespace SEBT.Portal.Infrastructure.Helpers;

/// <summary>
/// Factory for creating User and UserEntity instances using Bogus for generating fake data.
/// Used for both testing and database seeding.
/// See https://github.com/bchavez/Bogus for more information
/// </summary>
public static class UserFactory
{
    private static readonly Faker<User> UserFaker = new Faker<User>()
        .RuleFor(u => u.Id, f => 0) // Id is auto-generated by database, use 0 for new users
        .RuleFor(u => u.Email, f => f.Internet.Email().ToLowerInvariant())
        .RuleFor(u => u.IdProofingStatus, f => f.PickRandom<IdProofingStatus>())
        .RuleFor(u => u.IdProofingSessionId, f => f.Random.Guid().ToString())
        .RuleFor(u => u.IdProofingCompletedAt, (f, u) =>
            u.IdProofingStatus == IdProofingStatus.Completed || u.IdProofingStatus == IdProofingStatus.Expired
                ? f.Date.Recent(30)
                : null)
        .RuleFor(u => u.IdProofingExpiresAt, (f, u) =>
            u.IdProofingCompletedAt?.AddYears(1))
        .RuleFor(u => u.IsCoLoaded, f => f.Random.Bool(0.3f))
        .RuleFor(u => u.CoLoadedLastUpdated, (f, u) =>
            u.IsCoLoaded ? f.Date.Recent(60) : null)
        .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
        .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

    private static readonly Faker<UserEntity> UserEntityFaker = new Faker<UserEntity>()
        .RuleFor(u => u.Id, f => 0) // Id is auto-generated by database, use 0 for new entities
        .RuleFor(u => u.Email, f => f.Internet.Email().ToLowerInvariant())
        .RuleFor(u => u.IdProofingStatus, f => (int)f.PickRandom<IdProofingStatus>())
        .RuleFor(u => u.IdProofingSessionId, f => f.Random.Guid().ToString())
        .RuleFor(u => u.IdProofingCompletedAt, (f, u) =>
            u.IdProofingStatus == (int)IdProofingStatus.Completed || u.IdProofingStatus == (int)IdProofingStatus.Expired
                ? f.Date.Recent(30)
                : null)
        .RuleFor(u => u.IdProofingExpiresAt, (f, u) =>
            u.IdProofingCompletedAt?.AddYears(1))
        .RuleFor(u => u.IsCoLoaded, f => f.Random.Bool(0.3f))
        .RuleFor(u => u.CoLoadedLastUpdated, (f, u) =>
            u.IsCoLoaded ? f.Date.Recent(60) : null)
        .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
        .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

    /// <summary>
    /// Creates a new User instance with generated fake data.
    /// </summary>
    /// <param name="customize">Optional action to customize the generated user.</param>
    /// <returns>A new User instance.</returns>
    public static User CreateUser(Action<User>? customize = null)
    {
        var user = UserFaker.Generate();
        customize?.Invoke(user);
        return user;
    }

    /// <summary>
    /// Creates a new User instance with a specific email address.
    /// </summary>
    /// <param name="email">The email address to use.</param>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A new User instance with the specified email.</returns>
    public static User CreateUserWithEmail(string email, Action<User>? customize = null)
    {
        var user = UserFaker.Generate();
        // Email is now settable, so we can set it directly
        user.Email = email.ToLowerInvariant().Trim();
        customize?.Invoke(user);
        return user;
    }

    /// <summary>
    /// Creates a new UserEntity instance with realistic fake data.
    /// </summary>
    /// <param name="customize">Optional action to customize the generated entity.</param>
    /// <returns>A new UserEntity instance.</returns>
    public static UserEntity CreateUserEntity(Action<UserEntity>? customize = null)
    {
        var entity = UserEntityFaker.Generate();
        customize?.Invoke(entity);
        return entity;
    }

    /// <summary>
    /// Creates a User with co-loaded status set to true.
    /// </summary>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with IsCoLoaded = true.</returns>
    public static User CreateCoLoadedUser(Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IsCoLoaded = true;
            // Create a temporary faker for date generation (acceptable for single date value)
            var faker = new Faker();
            u.CoLoadedLastUpdated = faker.Date.Recent(60);
            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Creates a User with co-loaded status set to false.
    /// </summary>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with IsCoLoaded = false.</returns>
    public static User CreateNonCoLoadedUser(Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IsCoLoaded = false;
            u.CoLoadedLastUpdated = null;
            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Creates a UserEntity with co-loaded status set to true.
    /// </summary>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A UserEntity instance with IsCoLoaded = true.</returns>
    public static UserEntity CreateCoLoadedUserEntity(Action<UserEntity>? customize = null)
    {
        return CreateUserEntity(e =>
        {
            e.IsCoLoaded = true;
            // Create a temporary faker for date generation (acceptable for single date value)
            var faker = new Faker();
            e.CoLoadedLastUpdated = faker.Date.Recent(60);
            customize?.Invoke(e);
        });
    }

    /// <summary>
    /// Creates a UserEntity with co-loaded status set to false.
    /// </summary>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A UserEntity instance with IsCoLoaded = false.</returns>
    public static UserEntity CreateNonCoLoadedUserEntity(Action<UserEntity>? customize = null)
    {
        return CreateUserEntity(e =>
        {
            e.IsCoLoaded = false;
            e.CoLoadedLastUpdated = null;
            customize?.Invoke(e);
        });
    }

    /// <summary>
    /// Creates a User with a specific ID proofing status.
    /// </summary>
    /// <param name="status">The ID proofing status to set.</param>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with the specified ID proofing status.</returns>
    public static User CreateUserWithStatus(IdProofingStatus status, Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IdProofingStatus = status;

            // Set related dates based on status
            if (status == IdProofingStatus.Completed || status == IdProofingStatus.Expired)
            {
                // Create a temporary faker for date generation (acceptable for single date value)
                var faker = new Faker();
                u.IdProofingCompletedAt = faker.Date.Recent(30);
                u.IdProofingExpiresAt = u.IdProofingCompletedAt.Value.AddYears(1);
            }
            else
            {
                u.IdProofingCompletedAt = null;
                u.IdProofingExpiresAt = null;
            }

            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Sets a seed for the random number generator to ensure deterministic test data.
    /// </summary>
    /// <param name="seed">The seed value to use.</param>
    public static void SetSeed(int seed)
    {
        Randomizer.Seed = new Random(seed);
    }

    /// <summary>
    /// Creates a new UserEntity instance and saves it to the database.
    /// </summary>
    /// <param name="context">The database context to save the entity to.</param>
    /// <param name="customize">Optional action to customize the generated entity.</param>
    /// <returns>A new UserEntity instance that has been saved to the database (with Id populated).</returns>
    public static async Task<UserEntity> CreateAndSaveUserEntityAsync(
        PortalDbContext context,
        Action<UserEntity>? customize = null,
        CancellationToken cancellationToken = default)
    {
        var entity = CreateUserEntity(customize);
        context.Users.Add(entity);
        await context.SaveChangesAsync(cancellationToken);
        return entity;
    }

    /// <summary>
    /// Creates a new UserEntity instance with a specific email and saves it to the database.
    /// </summary>
    /// <param name="context">The database context to save the entity to.</param>
    /// <param name="email">The email address to use.</param>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A new UserEntity instance that has been saved to the database (with Id populated).</returns>
    public static async Task<UserEntity> CreateAndSaveUserEntityWithEmailAsync(
        PortalDbContext context,
        string email,
        Action<UserEntity>? customize = null,
        CancellationToken cancellationToken = default)
    {
        var entity = CreateUserEntity(e =>
        {
            e.Email = email.ToLowerInvariant().Trim();
            customize?.Invoke(e);
        });
        context.Users.Add(entity);
        await context.SaveChangesAsync(cancellationToken);
        return entity;
    }

    /// <summary>
    /// Creates a co-loaded UserEntity instance and saves it to the database.
    /// </summary>
    /// <param name="context">The database context to save the entity to.</param>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A new UserEntity instance with IsCoLoaded = true that has been saved to the database.</returns>
    public static async Task<UserEntity> CreateAndSaveCoLoadedUserEntityAsync(
        PortalDbContext context,
        Action<UserEntity>? customize = null,
        CancellationToken cancellationToken = default)
    {
        var entity = CreateCoLoadedUserEntity(customize);
        context.Users.Add(entity);
        await context.SaveChangesAsync(cancellationToken);
        return entity;
    }

    /// <summary>
    /// Creates a non-co-loaded UserEntity instance and saves it to the database.
    /// </summary>
    /// <param name="context">The database context to save the entity to.</param>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A new UserEntity instance with IsCoLoaded = false that has been saved to the database.</returns>
    public static async Task<UserEntity> CreateAndSaveNonCoLoadedUserEntityAsync(
        PortalDbContext context,
        Action<UserEntity>? customize = null,
        CancellationToken cancellationToken = default)
    {
        var entity = CreateNonCoLoadedUserEntity(customize);
        context.Users.Add(entity);
        await context.SaveChangesAsync(cancellationToken);
        return entity;
    }
}
