using Bogus;
using SEBT.Portal.Core.Models.Auth;
using SEBT.Portal.Infrastructure.Data.Entities;

namespace SEBT.Portal.Tests.Helpers;

/// <summary>
/// Factory for creating test User and UserEntity instances using Bogus for generating fake data.
/// See https://github.com/bchavez/Bogus for more information
/// </summary>
public static class UserFactory
{
    private static readonly Faker<User> UserFaker = new Faker<User>()
        .RuleFor(u => u.Id, f => 0) // Id is auto-generated by database, use 0 for new users
        .RuleFor(u => u.Email, f => f.Internet.Email().ToLowerInvariant())
        .RuleFor(u => u.IdProofingStatus, f => f.PickRandom<IdProofingStatus>())
        .RuleFor(u => u.IdProofingSessionId, f => f.Random.Guid().ToString())
        .RuleFor(u => u.IdProofingCompletedAt, (f, u) =>
            u.IdProofingStatus == IdProofingStatus.Completed || u.IdProofingStatus == IdProofingStatus.Expired
                ? f.Date.Recent(30)
                : null)
        .RuleFor(u => u.IdProofingExpiresAt, (f, u) =>
            u.IdProofingCompletedAt?.AddYears(1))
        .RuleFor(u => u.IsCoLoaded, f => f.Random.Bool(0.3f))
        .RuleFor(u => u.CoLoadedLastUpdated, (f, u) =>
            u.IsCoLoaded ? f.Date.Recent(60) : null)
        .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
        .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

    private static readonly Faker<UserEntity> UserEntityFaker = new Faker<UserEntity>()
        .RuleFor(u => u.Id, f => 0) // Id is auto-generated by database, use 0 for new entities
        .RuleFor(u => u.Email, f => f.Internet.Email().ToLowerInvariant())
        .RuleFor(u => u.IdProofingStatus, f => (int)f.PickRandom<IdProofingStatus>())
        .RuleFor(u => u.IdProofingSessionId, f => f.Random.Guid().ToString())
        .RuleFor(u => u.IdProofingCompletedAt, (f, u) =>
            u.IdProofingStatus == (int)IdProofingStatus.Completed || u.IdProofingStatus == (int)IdProofingStatus.Expired
                ? f.Date.Recent(30)
                : null)
        .RuleFor(u => u.IdProofingExpiresAt, (f, u) =>
            u.IdProofingCompletedAt?.AddYears(1))
        .RuleFor(u => u.IsCoLoaded, f => f.Random.Bool(0.3f))
        .RuleFor(u => u.CoLoadedLastUpdated, (f, u) =>
            u.IsCoLoaded ? f.Date.Recent(60) : null)
        .RuleFor(u => u.CreatedAt, f => f.Date.Past(1))
        .RuleFor(u => u.UpdatedAt, (f, u) => f.Date.Between(u.CreatedAt, DateTime.UtcNow));

    /// <summary>
    /// Creates a new User instance with generated fake data.
    /// </summary>
    /// <param name="customize">Optional action to customize the generated user.</param>
    /// <returns>A new User instance.</returns>
    public static User CreateUser(Action<User>? customize = null)
    {
        var user = UserFaker.Generate();
        customize?.Invoke(user);
        return user;
    }

    /// <summary>
    /// Creates a new User instance with a specific email address.
    /// </summary>
    /// <param name="email">The email address to use.</param>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A new User instance with the specified email.</returns>
    public static User CreateUserWithEmail(string email, Action<User>? customize = null)
    {
        var user = UserFaker.Generate();
        // Email is now settable, so we can set it directly
        user.Email = email.ToLowerInvariant().Trim();
        customize?.Invoke(user);
        return user;
    }

    /// <summary>
    /// Creates a new UserEntity instance with realistic fake data.
    /// </summary>
    /// <param name="customize">Optional action to customize the generated entity.</param>
    /// <returns>A new UserEntity instance.</returns>
    public static UserEntity CreateUserEntity(Action<UserEntity>? customize = null)
    {
        var entity = UserEntityFaker.Generate();
        customize?.Invoke(entity);
        return entity;
    }

    /// <summary>
    /// Creates a User with co-loaded status set to true.
    /// </summary>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with IsCoLoaded = true.</returns>
    public static User CreateCoLoadedUser(Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IsCoLoaded = true;
            // Use Bogus's randomizer for consistency with other factory methods
            var faker = new Faker();
            u.CoLoadedLastUpdated = faker.Date.Recent(60);
            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Creates a User with co-loaded status set to false.
    /// </summary>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with IsCoLoaded = false.</returns>
    public static User CreateNonCoLoadedUser(Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IsCoLoaded = false;
            u.CoLoadedLastUpdated = null;
            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Creates a UserEntity with co-loaded status set to true.
    /// </summary>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A UserEntity instance with IsCoLoaded = true.</returns>
    public static UserEntity CreateCoLoadedUserEntity(Action<UserEntity>? customize = null)
    {
        return CreateUserEntity(e =>
        {
            e.IsCoLoaded = true;
            // Use Bogus's randomizer for consistency with other factory methods
            var faker = new Faker();
            e.CoLoadedLastUpdated = faker.Date.Recent(60);
            customize?.Invoke(e);
        });
    }

    /// <summary>
    /// Creates a UserEntity with co-loaded status set to false.
    /// </summary>
    /// <param name="customize">Optional action to further customize the entity.</param>
    /// <returns>A UserEntity instance with IsCoLoaded = false.</returns>
    public static UserEntity CreateNonCoLoadedUserEntity(Action<UserEntity>? customize = null)
    {
        return CreateUserEntity(e =>
        {
            e.IsCoLoaded = false;
            e.CoLoadedLastUpdated = null;
            customize?.Invoke(e);
        });
    }

    /// <summary>
    /// Creates a User with a specific ID proofing status.
    /// </summary>
    /// <param name="status">The ID proofing status to set.</param>
    /// <param name="customize">Optional action to further customize the user.</param>
    /// <returns>A User instance with the specified ID proofing status.</returns>
    public static User CreateUserWithStatus(IdProofingStatus status, Action<User>? customize = null)
    {
        return CreateUser(u =>
        {
            u.IdProofingStatus = status;

            // Set related dates based on status
            if (status == IdProofingStatus.Completed || status == IdProofingStatus.Expired)
            {
                // Use Bogus's randomizer for consistency with other factory methods
                var faker = new Faker();
                u.IdProofingCompletedAt = faker.Date.Recent(30);
                u.IdProofingExpiresAt = u.IdProofingCompletedAt.Value.AddYears(1);
            }
            else
            {
                u.IdProofingCompletedAt = null;
                u.IdProofingExpiresAt = null;
            }

            customize?.Invoke(u);
        });
    }

    /// <summary>
    /// Sets a seed for the random number generator to ensure deterministic test data.
    /// </summary>
    /// <param name="seed">The seed value to use.</param>
    public static void SetSeed(int seed)
    {
        Randomizer.Seed = new Random(seed);
    }
}
