import { getStateConfig, type StateCode } from '@sebt/design-system'
import i18next, { type Resource } from 'i18next'
import { describe, expect, it } from 'vitest'

import { stateResources } from '@/lib/generated-locale-resources'
import { PROVISIONAL_EN } from '@/lib/provisionalContent'

import { APPLICATION_STATUS_KEYS } from './ApplicationsSection/ApplicationsSection'
import { PROFILE_STATUS_LABEL_KEYS } from './HouseholdSummary/HouseholdSummary'

/**
 * Guards the "never show a raw backend code" half of the dashboard status contract.
 *
 * The status labels carry no `t()` fallback — see .claude/rules/localization.md — so a missing
 * or blank content cell reaches the user directly. i18next returns the key itself when a
 * translation is missing everywhere, and an empty string when the key exists with an empty
 * value. Both render as garbage: a guardian sees the literal text `profileTableStatusUnknown`,
 * or a blank status. Neither throws, so nothing else in the suite would notice.
 *
 * This resolves each key through a real i18next instance configured like the app's, so it
 * measures what a user sees rather than what is in a JSON file. That means it accounts for both
 * `fallbackLng: 'en'` and the provisional English bundle, and it still catches a blank cell,
 * because an empty value is returned as-is rather than falling back.
 *
 * A failure is a content gap, not a code bug. Fix the CSV and the upstream sheet; locale JSON is
 * generated by `pnpm copy:generate` and must never be hand-edited.
 */

const STATES: readonly StateCode[] = ['dc', 'co']

const STATUS_LABEL_KEYS = [...Object.values(APPLICATION_STATUS_KEYS), ...PROFILE_STATUS_LABEL_KEYS]

function bundlesFor(state: StateCode) {
  // eslint-disable-next-line security/detect-object-injection -- state comes from the STATES literal
  return stateResources[state]
}

/** Mirrors src/lib/i18n-init.ts, for one state and one language. */
async function translatorFor(state: StateCode, language: string) {
  const instance = i18next.createInstance()
  await instance.init({
    lng: language,
    fallbackLng: 'en',
    ns: ['dashboard'],
    defaultNS: 'dashboard',
    resources: bundlesFor(state) as Resource
  })

  for (const [namespace, resources] of Object.entries(PROVISIONAL_EN)) {
    instance.addResourceBundle('en', namespace, resources, true, false)
  }

  return instance
}

describe('dashboard status label coverage', () => {
  it('exercises every status label the dashboard can render', () => {
    // Sanity check on the fixture: if a component stops exporting its keys, the loops below
    // would silently pass over an empty list.
    expect(STATUS_LABEL_KEYS.length).toBe(12)
  })

  describe.each(STATES)('%s', (state) => {
    const languages = getStateConfig(state).supportedLanguages

    it.each(languages)('ships a dashboard bundle for %s', (language) => {
      const bundles = bundlesFor(state) as Record<string, Record<string, unknown>> | undefined
      // eslint-disable-next-line security/detect-object-injection -- language comes from the state config
      expect(bundles?.[language]?.dashboard).toBeDefined()
    })

    describe.each(languages)('%s', (language) => {
      it.each(STATUS_LABEL_KEYS)('resolves %s to human-readable copy', async (key) => {
        const instance = await translatorFor(state, language)
        const rendered = instance.t(key)

        expect(rendered, `"${key}" is unauthored and has no provisional English`).not.toBe(key)
        expect(rendered, `"${key}" resolves to an empty string`).not.toBe('')
      })
    })
  })
})
